# Example/Documentation for this file
# https://fshschool.org/docs/sushi/configuration/#exhaustive-example

id: ch.ahdis.ig.ch-rad-poc
canonical: http://ahdis.ch/ig/ch-rad-poc
name: CH_RAD_POC
title: "CH RAD-ProofOfConcept (R4)"
description: Implementation guide CH RAD Proof Of Concept (R4)
status: active
license: CC-BY-SA-4.0
copyright: CC-BY-SA-4.0
jurisdiction: urn:iso:std:iso:3166#CH
date: 2021-10-25
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2021+
releaseLabel: STU 1
publisher:
  name: ahdis
contact:
  name: Oliver Egger
  telecom:
    system: url
    value: https://www.ahdis.ch
dependencies:
  ch.fhir.ig.ch-orf: 0.10.0
  ch.fhir.ig.ch-core: 2.0.0
  ch.fhir.ig.ch-rad-order: 0.1.0
  ch.fhir.ig.ch-epr-mhealth: 0.2.0
pages:
  index.html:
    title: Home
  usecase-english.md:
    title: Use Cases
  usecase-german.md:
    title: Anwendungsfälle
  usecase-french.md:
    title: Cas d'application
  questionnaire.html:
    title: Questionnaire
  profiles.html:
    title: Profiles
  extensions.html:
    title: Extensions
  terminology.html:
    title: Terminology