id: ch.fhir.ig.ch-rad-order
canonical: http://fhir.ch/ig/ch-rad-order
name: CH_RAD_Order
title: "CH RAD-Order (R4)"
description: Implementation guide for dental data from Straumann
status: draft
license: CC-BY-SA-4.0
copyright: CC-BY-SA-4.0
jurisdiction: urn:iso:std:iso:3166#CH
date: 2021-01-14
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2021+
releaseLabel: ci-build
publisher:
  name: eHealth Suisse
contact:
  name: eHealth Suisse
  telecom:
    system: url
    value: https://www.e-health-suisse.ch/startseite.html
dependencies:
  ch.fhir.ig.ch-orf: current
  ch.fhir.ig.ch-core: 1.2.0

