@host = https://test.ahdis.ch/matchbox/fhir

### Setup for RadOrder PoC

PUT {{host}}/Questionnaire/QuestionnaireRadiologyOrderPoC
Content-Type: application/json+fhir

< output/Questionnaire-QuestionnaireRadiologyOrderPoC.json

### Setup Default Questionnaire for Prefilled Items

PUT {{host}}/QuestionnaireResponse/SenderPrefilledQuestionnaireResponse
Content-Type: application/json+fhir

< output/QuestionnaireResponse-SenderPrefilledQuestionnaireResponse.json

###
GET {{host}}/QuestionnaireResponse?_sort=-_lastUpdated
Content-Type: application/json+fhir


### [01] Create a rad-order

###      Setup Bundle as Radiology Order
PUT {{host}}/Bundle/bundle-order1 HTTP/1.1
Content-Type: application/json+fhir

< output/Bundle-bundle-order1.json

###      Setup Reference to original ImagingStudy
PUT {{host}}/ImagingStudy/imagingstudy-order1 HTTP/1.1
Content-Type: application/json+fhirmvn clean package -DskipTests

< output/ImagingStudy-imagingstudy-order1.json

###      Create Task referencing Bundle and ImagingStudy
PUT {{host}}/Task/task-order1 HTTP/1.1
Content-Type: application/json+fhir

< output/Task-task-order1.json

### [02] Get Rad-order

###      Poll for ready tasks
GET {{host}}/Task?status=ready HTTP/1.1
Accept: application/json+fhir

###      Get task that 
###      This could be used to get bundle directly, but there is no references search parameter for input Task?_id=task-order1&_include=Task:focus could be
GET {{host}}/Task/task-order1 HTTP/1.1
Accept: application/json+fhir


###      Udpate the task, set status to completed 
###      This could be used to get bundle directly, but there is no references search parameter for input Task?_id=task-order1&_include=Task:focus could be
GET {{host}}/ImagingStudy/imagingstudy-order1 HTTP/1.1
Accept: application/json+fhir

###
GET {{host}}/Bundle/bundle-order1 HTTP/1.1
Accept: application/json+fhir

###
GET {{host}}/ImagingStudy/imagingstudy-order1 HTTP/1.1
Accept: application/json+fhir

###     Update Task to in-progress, adjust modified and add new owner via JSON Patch
PATCH {{host}}/Task/task-order1 HTTP/1.1
Content-Type: application/json-patch+json

[ 
    {  "op": "replace", "path": "/status", "value": "in-progress" },
    {  "op": "replace", "path": "/lastModified", "value": "2021-10-27T15:46:34+02:00" },
    {  "op": "add", "path": "/owner", "value": { "identifier":   { "system" : "urn:oid:2.999.1.2.3", "value" : "tbd" },  "display": "Intermediary" } }
]

###      Create Task referencing Bundle and ImagingStudy (need to adjsut the id in ask-task-order1-inprogress)
PUT {{host}}/Task/task-order1 HTTP/1.1
Content-Type: application/json+fhir

< output/Task-task-order1-inprogress.json



### [06] Create Radiology Order
POST {{host}}/ HTTP/1.1
Content-Type: application/json+fhir

< output/Bundle-order1-filler-transaction.json

###
@task-id = 1279
###      "response": {
###        "status": "201 Created",
###        "location": "Task/1279/_history/1",
###        "etag": "1",
###        "lastModified": "2021-10-28T11:06:11.980+00:00"
###      }
GET {{host}}/Task/{{task-id}} HTTP/1.1
Accept: application/json+fhir


### [07] Get new Radiology Order

GET {{host}}/Task?status=ready
Accept: application/json+fhir


### [09] Update Radiology Order
### note you need to remove the id in the Task-order-filler otherwise the update does nt work
POST {{host}}/ HTTP/1.1
Content-Type: application/json+fhir

< output/Bundle-order1-update-filler-transaction.json


### Get PDF Report with references to imaging studies [10]
GET {{host}}/Task?status=completed&&modified=gt2021-10-27T14:56:58+02:00
Accept: application/json+fhir

### Set Radiology Order to completed [14] 
### note you need to remove the id in the Task-order-filler otherwise the update does nt work
POST {{host}}/ HTTP/1.1
Content-Type: application/json+fhir

< output/Bundle-order1-update-placer-complete-transaction.json

###      Poll for ready tasks
GET {{host}}/Task?status=completed HTTP/1.1
Accept: application/json+fhir


###
POST {{host}}/Questionnaire HTTP/1.1
Content-Type: application/xml+fhir

< /Users/oliveregger/Documents/github/sdc/input/examples/questionnaire-sdc-profile-example-form-behavior.xml


###
POST {{host}}/Questionnaire HTTP/1.1
Content-Type: application/json+fhir

< ./test-initial-value.json