Alias: $sct = http://snomed.info/sct

Instance: SenderPrefilledQuestionnaireResponse
InstanceOf: QuestionnaireResponse
Usage: #example
* identifier.system = "http://ahdis.ch/fhir/Questionnaire"
* identifier.value = "DEFAULT"
* questionnaire = "http://fhir.ch/ig/ch-rad-order/Questionnaire/QuestionnaireRadiologyOrderPoC"
* status = #completed
* item[0].linkId = "order"
* item[=].text = "Auftrag"
* item[=].item[0].linkId = "order.title"
* item[=].item[=].text = "Titel"
* item[=].item[=].answer.valueString = "Anmeldung Radiologie"
* item[=].item[+].linkId = "order.type"
* item[=].item[=].text = "Typ"
* item[=].item[=].answer.valueCoding = urn:oid:2.16.756.5.30.1.127.3.4#2161000195103 "Imaging order (record artifact)"
* item[=].item[+].linkId = "order.category"
* item[=].item[=].text = "Kategorie"
* item[=].item[=].answer.valueCoding = $sct#721963009 "Order (record artifact)"
* item[=].item[+].linkId = "order.placerOrderIdentifierDomain"
* item[=].item[=].text = "Identifier Domain der Auftragsnummer des Auftraggebers"
* item[=].item[=].answer.valueString = "urn:oid:2.16.756.5.30.1.145.1.2.3"
* item[+].linkId = "patient"
* item[=].text = "Patient"
* item[=].item.linkId = "patient.localPidDomain"
* item[=].item.text = "Lokale Patienten-ID Domain"
* item[=].item.answer.valueString = "urn:oid:2.16.756.5.30.1.145.1.9.9"
* item[+].linkId = "sender"
* item[=].text = "Absender"
* item[=].item.linkId = "sender.author"
* item[=].item.text = "Verantwortlicher"
* item[=].item.item.linkId = "sender.author.organization"
* item[=].item.item.text = "Verantwortliche Organisation"
* item[=].item.item.item[0].linkId = "sender.author.organization.name"
* item[=].item.item.item[=].text = "Name der Organisation"
* item[=].item.item.item[=].answer.valueString = "SUVA (Test)"
* item[=].item.item.item[+].linkId = "sender.author.organization.gln"
* item[=].item.item.item[=].text = "GLN"
* item[=].item.item.item[=].answer.valueString = "7601003001136"
* item[=].item.item.item[+].linkId = "sender.author.organization.streetAddressLine"
* item[=].item.item.item[=].text = "Strasse, Hausnummer, Postfach etc."
* item[=].item.item.item[=].answer.valueString = "Fluhmattstrasse 1"
* item[=].item.item.item[+].linkId = "sender.author.organization.postalCode"
* item[=].item.item.item[=].text = "PLZ"
* item[=].item.item.item[=].answer.valueString = "6004"
* item[=].item.item.item[+].linkId = "sender.author.organization.city"
* item[=].item.item.item[=].text = "Ort"
* item[=].item.item.item[=].answer.valueString = "Luzern"
* item[=].item.item.item[+].linkId = "sender.author.organization.country"
* item[=].item.item.item[=].text = "Land"
* item[=].item.item.item[=].answer.valueString = "Schweiz"
* item[+].linkId = "receiver"
* item[=].text = "Empfänger"
* item[=].item.linkId = "receiver.organization"
* item[=].item.text = "Empfangende Organisation"
* item[=].item.item[0].linkId = "receiver.organization.name"
* item[=].item.item[=].text = "Name der Organisation"
* item[=].item.item[=].answer.valueString = "ahdis (Test)"
* item[=].item.item[+].linkId = "receiver.organization.gln"
* item[=].item.item[=].text = "GLN"
* item[=].item.item[=].answer.valueString = "7601001401310"