version: '3'
services:
  matchbox-formfiller:
    image: eu.gcr.io/fhir-ch/matchbox-formfiller:v172
    restart: on-failure
    ports:
      - '4300:80'
    links:
      - matchbox
    environment:
      DOMAIN: 'localhost'
      MAG: 'https://test.ahdis.ch/mag-pmp'
      MATCHBOX: 'http://matchbox:8080/matchbox'
  matchbox:
    image: eu.gcr.io/fhir-ch/matchbox:v170
    container_name: matchbox
    restart: on-failure
    ports:
      - '8080:8080'
    links:
      - matchbox-db
    volumes:
      - .:/config
  matchbox-db:
    image: postgres:latest
    container_name: matchbox-db
    restart: always
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: 'matchbox'
      POSTGRES_USER: 'matchbox'
      POSTGRES_PASSWORD: 'matchbox'
    volumes:
      - ./data:/var/lib/postgresql/data
